In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('nonlinear_data.csv')
df.head()

,X1,X2,target
0,-0.375222,0.251247,1
1,0.029190,1.027463,0
2,-0.314708,0.032279,1
3,-0.553103,-0.604837,0
4,-0.751558,0.774967,0


In [4]:
X=df.iloc[:,0:2]
X

,X1,X2
0,-0.375222,0.251247
1,0.029190,1.027463
2,-0.314708,0.032279
3,-0.553103,-0.604837
4,-0.751558,0.774967
...,...,...
495,-0.862768,0.497316
496,0.471954,-0.003795
497,-0.556110,0.488220
498,-0.240691,-0.582546


In [5]:
y=df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      0
      ..
495    0
496    1
497    1
498    1
499    0
Name: target, Length: 500, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2, random_state=2)

In [17]:
from sklearn.preprocessing import PolynomialFeatures
polyf=PolynomialFeatures(2)

In [18]:
X_train_trans=polyf.fit_transform(X_train)
X_test_trans=polyf.fit_transform(X_test)

In [19]:
X_train_trans[0]

array([1.        , 0.21900476, 0.14214831, 0.04796309, 0.03113116,
       0.02020614])

In [20]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()

In [21]:
logr.fit(X_train_trans,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [24]:
y_predict=logr.predict(X_test_trans)

In [26]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.98


In [27]:
logr.coef_

array([[ 1.43407064e-03,  2.68477715e-01, -8.46073237e-02,
        -5.39533326e+00, -2.10014520e-01, -5.82722677e+00]])

In [28]:
logr.intercept_

array([3.08811224])