In [36]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [11]:
X,y= load_diabetes (return_X_y=True)

In [12]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [18]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [19]:
from sklearn.model_selection import train_test_split

In [25]:
X_test,X_train, y_test, y_train= train_test_split(X,y ,test_size= 0.2, random_state=2)

In [43]:
y_train

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [26]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [27]:
lr.coef_

array([ -51.35911041, -350.59199347,  499.98352483,  271.14146179,
       -107.9136373 ,   33.02675986, -320.47288819,  140.97466206,
        236.06227253,  164.3980547 ])

In [28]:
lr.intercept_

np.float64(151.17244580700347)

In [57]:
lr.predict([X_train[0]])

array([145.3432265])

In [53]:
y_pred= lr.predict(X_test)

In [54]:
from sklearn.metrics import r2_score

In [56]:
r2_score(y_test, y_pred)

0.4851449923360439

## My OWN CLASS

In [69]:
class my_mlr:
    def __init__(self):
        self.coefff=None
        self.intercpt=None

    def fit(X_train,y_train):
        # np.insert(array, index no, changes   , axis=)
        np.insert(X_train, 0, 1 , axis= 1)

    def predict(self,X_test):
        pass
        

In [67]:
lr= my_mlr
lr.fit(X_train,y_train)

In [68]:
X_train

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

In [70]:
np.insert(X_train, 0, 1 , axis= 1)

array([[ 1.00000000e+00,  6.71362140e-02, -4.46416365e-02,
         3.49435453e-03,  3.56437894e-02,  4.93412959e-02,
         3.12535626e-02,  7.07299263e-02, -3.94933829e-02,
        -6.11735305e-04,  1.96328371e-02],
       [ 1.00000000e+00, -7.81653240e-02,  5.06801187e-02,
         7.78633876e-02,  5.28580443e-02,  7.82363060e-02,
         6.44472995e-02,  2.65502726e-02, -2.59226200e-03,
         4.06728289e-02, -9.36191133e-03],
       [ 1.00000000e+00,  4.17084449e-02,  5.06801187e-02,
        -1.48284507e-02, -1.71351160e-02, -5.69681839e-03,
         8.39372489e-03, -1.39477432e-02, -1.85423958e-03,
        -1.18968513e-02,  3.06440941e-03],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02,
        -4.82406250e-02, -1.94418262e-02, -1.93006962e-04,
        -1.60318551e-02,  6.70482885e-02, -3.94933829e-02,
        -2.47954290e-02,  1.96328371e-02],
       [ 1.00000000e+00,  9.01559883e-03,  5.06801187e-02,
         6.92408910e-02,  5.97437462e-02,  1.76943802e-02,
  