In [73]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [74]:
X,y= load_diabetes (return_X_y=True)

In [75]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [76]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_test,X_train, y_test, y_train= train_test_split(X,y ,test_size= 0.2, random_state=2)

In [79]:
y_train

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [80]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [81]:
lr.coef_

array([ -51.35911041, -350.59199347,  499.98352483,  271.14146179,
       -107.9136373 ,   33.02675986, -320.47288819,  140.97466206,
        236.06227253,  164.3980547 ])

In [82]:
lr.intercept_

np.float64(151.17244580700347)

In [83]:
lr.predict(X_test)

array([ 91.8826939 , 146.45458842,  62.7942858 , 178.26121497,
        59.77556542, 164.4013517 , 245.96276614, 140.55682359,
       193.33973394, 166.82893236, 170.05751261, 108.78511874,
       143.51807195, 113.45371646, 177.1821666 , 162.67111642,
       172.88235427,  98.87597882, 125.51281101, 172.31799082,
       146.90939093, 206.51084511, 155.94527296, 221.93606362,
       162.04802666,  81.04366063, 112.3560719 ,  90.38418622,
       156.13166529, 140.60857311,  88.92178439, 208.02606186,
       267.92175207, 172.10725692, 194.86785287, 243.65091241,
       186.52991135, 182.81393293,  64.75472222, 165.83042881,
        56.89167283, 124.45791505, 108.46399063, 105.40289424,
       146.92380244,  37.86991878, 114.31429819, 175.37355412,
       144.68390586, 175.21797019, 212.27544547, 248.66852651,
       199.86426458, 143.40529319, 136.25672764, 125.45532936,
       139.65189169,  91.20393772, 141.73242403,  94.94980657,
       232.6323158 ,  85.35220146, 180.54222271,  87.10

In [84]:
y_pred= lr.predict(X_test)

In [85]:
from sklearn.metrics import r2_score

In [86]:
r2_score(y_test, y_pred)

0.4851449923360439